# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host = localhost
@port = 8080
@baseUrl = http://{{host}}:{{port}}

### Artist Details By ID
GET {{baseUrl}}/artist/6512329
Accept: application/json

### Album Rating
PUT {{baseUrl}}/rating
Content-Type: application/json
{
  "UserId": 1,
  "AlbumId": 3540664,
  "Score": 8,
  "Review": "Her best work so far."
}

### Album Rating To Check Update (Not Dupe)
PUT {{baseUrl}}/rating
Content-Type: application/json
{
  "UserId": 1,
  "AlbumId": 3540664,
  "Score": 8,
  "Review": "Her best work so far."
}