// <auto-generated />
using System;
using MediaBoard.Server.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaBoard.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624010735_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlbumArtist", b =>
                {
                    b.Property<int>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("album_id");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.HasKey("AlbumId", "ArtistId")
                        .HasName("album_artist_pkey");

                    b.HasIndex(new[] { "AlbumId" }, "ix_album_artist_album_id");

                    b.HasIndex(new[] { "ArtistId" }, "ix_album_artist_artist_id");

                    b.ToTable("album_artist", (string)null);
                });

            modelBuilder.Entity("AlbumGenre", b =>
                {
                    b.Property<int>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("album_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.HasKey("AlbumId", "GenreId")
                        .HasName("album_genre_pkey");

                    b.HasIndex("GenreId");

                    b.ToTable("album_genre", (string)null);
                });

            modelBuilder.Entity("AlbumStyle", b =>
                {
                    b.Property<int>("AlbumId")
                        .HasColumnType("integer")
                        .HasColumnName("album_id");

                    b.Property<int>("StyleId")
                        .HasColumnType("integer")
                        .HasColumnName("style_id");

                    b.HasKey("AlbumId", "StyleId")
                        .HasName("album_style_pkey");

                    b.HasIndex("StyleId");

                    b.ToTable("album_style", (string)null);
                });

            modelBuilder.Entity("MediaBoard.Server.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int?>("MainId")
                        .HasColumnType("integer")
                        .HasColumnName("main_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("album_pkey");

                    b.ToTable("album", (string)null);
                });

            modelBuilder.Entity("MediaBoard.Server.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("app_user_pkey");

                    b.HasIndex(new[] { "Email" }, "app_user_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "app_user_username_key")
                        .IsUnique();

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("MediaBoard.Server.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RealName")
                        .HasColumnType("text")
                        .HasColumnName("real_name");

                    b.HasKey("Id")
                        .HasName("artist_pkey");

                    b.HasIndex(new[] { "Name" }, "artist_name_index");

                    b.ToTable("artist", (string)null);
                });

            modelBuilder.Entity("MediaBoard.Server.Entities.ArtistMetric", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.Property<int?>("TotalClicks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_clicks");

                    b.HasKey("ArtistId")
                        .HasName("artist_metrics_pkey");

                    b.ToTable("artist_metrics", (string)null);
                });

            modelBuilder.Entity("MediaBoard.Server.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("genre_pkey");

                    b.ToTable("genre", (string)null);
                });

            modelBuilder.Entity("MediaBoard.Server.Entities.MusicStyle", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("music_style_pkey");

                    b.ToTable("music_style", (string)null);
                });

            modelBuilder.Entity("MediaBoard.Server.Entities.Rating", b =>
                {
                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("media_id");

                    b.Property<string>("Review")
                        .HasColumnType("text")
                        .HasColumnName("review");

                    b.Property<short?>("Score")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasIndex("UserId");

                    b.ToTable("rating", (string)null);
                });

            modelBuilder.Entity("MediaBoard.Server.Entities.SearchRanking", b =>
                {
                    b.Property<long?>("AlbumCount")
                        .HasColumnType("bigint")
                        .HasColumnName("album_count");

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer")
                        .HasColumnName("artist_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("RankScore")
                        .HasColumnType("bigint")
                        .HasColumnName("rank_score");

                    b.Property<int?>("TotalClicks")
                        .HasColumnType("integer")
                        .HasColumnName("total_clicks");

                    b.ToTable((string)null);

                    b.ToView("search_ranking", (string)null);
                });

            modelBuilder.Entity("AlbumArtist", b =>
                {
                    b.HasOne("MediaBoard.Server.Entities.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("album_artist_album_id_fkey");

                    b.HasOne("MediaBoard.Server.Entities.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("album_artist_artist_id_fkey");
                });

            modelBuilder.Entity("AlbumGenre", b =>
                {
                    b.HasOne("MediaBoard.Server.Entities.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("album_genre_album_id_fkey");

                    b.HasOne("MediaBoard.Server.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("album_genre_genre_id_fkey");
                });

            modelBuilder.Entity("AlbumStyle", b =>
                {
                    b.HasOne("MediaBoard.Server.Entities.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("album_style_album_id_fkey");

                    b.HasOne("MediaBoard.Server.Entities.MusicStyle", null)
                        .WithMany()
                        .HasForeignKey("StyleId")
                        .IsRequired()
                        .HasConstraintName("album_style_style_id_fkey");
                });

            modelBuilder.Entity("MediaBoard.Server.Entities.ArtistMetric", b =>
                {
                    b.HasOne("MediaBoard.Server.Entities.Artist", "Artist")
                        .WithOne("ArtistMetric")
                        .HasForeignKey("MediaBoard.Server.Entities.ArtistMetric", "ArtistId")
                        .IsRequired()
                        .HasConstraintName("artist_metrics_artist_id_fkey");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MediaBoard.Server.Entities.Rating", b =>
                {
                    b.HasOne("MediaBoard.Server.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("rating_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediaBoard.Server.Entities.Artist", b =>
                {
                    b.Navigation("ArtistMetric");
                });
#pragma warning restore 612, 618
        }
    }
}
