# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host = localhost
@port = 5028
@baseUrl = http://{{host}}:{{port}}

### Search Artist
GET {{baseUrl}}/artist?query=Clairo&limit=15
Accept: application/json

### Artist Details By ID
GET {{baseUrl}}/artist/6512329
Accept: application/json